In [ ]:
import numpy as np

vector = np.array([
                   [-10, -10],
                   [-1, -1],
                    [0.5, 0.5],
                    [1, 1],
                    [100, 100],
                   [0, 100000],
                   ])

norm_vector = vector / ((np.sum(vector ** 2, axis = 1)) ** 0.5).reshape(-1, 1)

In [ ]:
np.dot(vector, vector.T)

array([[ 2.e+02,  2.e+01, -1.e+01, -2.e+01, -2.e+03, -1.e+06],
       [ 2.e+01,  2.e+00, -1.e+00, -2.e+00, -2.e+02, -1.e+05],
       [-1.e+01, -1.e+00,  5.e-01,  1.e+00,  1.e+02,  5.e+04],
       [-2.e+01, -2.e+00,  1.e+00,  2.e+00,  2.e+02,  1.e+05],
       [-2.e+03, -2.e+02,  1.e+02,  2.e+02,  2.e+04,  1.e+07],
       [-1.e+06, -1.e+05,  5.e+04,  1.e+05,  1.e+07,  1.e+10]])

In [ ]:
np.dot(norm_vector, norm_vector.T)

array([[ 1.        ,  1.        , -1.        , -1.        , -1.        ,
        -0.70710678],
       [ 1.        ,  1.        , -1.        , -1.        , -1.        ,
        -0.70710678],
       [-1.        , -1.        ,  1.        ,  1.        ,  1.        ,
         0.70710678],
       [-1.        , -1.        ,  1.        ,  1.        ,  1.        ,
         0.70710678],
       [-1.        , -1.        ,  1.        ,  1.        ,  1.        ,
         0.70710678],
       [-0.70710678, -0.70710678,  0.70710678,  0.70710678,  0.70710678,
         1.        ]])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity(vector, vector)

array([[ 1.        ,  1.        , -1.        , -1.        , -1.        ,
        -0.70710678],
       [ 1.        ,  1.        , -1.        , -1.        , -1.        ,
        -0.70710678],
       [-1.        , -1.        ,  1.        ,  1.        ,  1.        ,
         0.70710678],
       [-1.        , -1.        ,  1.        ,  1.        ,  1.        ,
         0.70710678],
       [-1.        , -1.        ,  1.        ,  1.        ,  1.        ,
         0.70710678],
       [-0.70710678, -0.70710678,  0.70710678,  0.70710678,  0.70710678,
         1.        ]])

In [ ]:
cosine_similarity(norm_vector, norm_vector)

array([[ 1.        ,  1.        , -1.        , -1.        , -1.        ,
        -0.70710678],
       [ 1.        ,  1.        , -1.        , -1.        , -1.        ,
        -0.70710678],
       [-1.        , -1.        ,  1.        ,  1.        ,  1.        ,
         0.70710678],
       [-1.        , -1.        ,  1.        ,  1.        ,  1.        ,
         0.70710678],
       [-1.        , -1.        ,  1.        ,  1.        ,  1.        ,
         0.70710678],
       [-0.70710678, -0.70710678,  0.70710678,  0.70710678,  0.70710678,
         1.        ]])

벡터를 정규화 하고 내적 유사도를 계산한다면 코사인 유사도와 동일하다는 것을 알 수 있음