<a href="https://colab.research.google.com/github/SeongBeomLEE/Study/blob/main/DataStudy/%EC%9D%B8%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
df = pd.DataFrame(
    {"label":items}
)
df

label
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

# 라벨 인코딩

카테고리 범주를 0 ~...까지의 숫자로 변환하는 것

In [21]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

encoder.fit(df['label'])
labels = encoder.transform(df['label'])

print('인코팅 변환 값:  ', labels)
print('인코팅 클래스 :  ', encoder.classes_)
print('디코딩 원본 값:  ', encoder.inverse_transform(labels))

df['LabelEncoder'] = labels
df['Decoding'] = encoder.inverse_transform(labels)

df

인코팅 변환 값:   [0 1 4 5 3 3 2 2]
인코팅 클래스 :   ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본 값:   ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


label  LabelEncoder Decoding
0     TV             0       TV
1    냉장고             1      냉장고
2  전자레인지             4    전자레인지
3    컴퓨터             5      컴퓨터
4    선풍기             3      선풍기
5    선풍기             3      선풍기
6     믹서             2       믹서
7     믹서             2       믹서

# 원핫 인코딩
칼럼 속 존재하는 n개의 카테고리에 각 카테고리에 해당하면 1 아니면 0으로 변환하여 n개의 컬럼을 만드는 것

## 방법 1

In [22]:
items = df['label'].values

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("변환 전: ", labels)

# 2차원으로 변환
labels = labels.reshape(-1,1)
print("변환 후: ", labels)

변환 전:  [0 1 4 5 3 3 2 2]
변환 후:  [[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]


In [23]:
from sklearn.preprocessing import OneHotEncoder
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print("원핫 인코딩 데이터")
print(oh_labels.toarray())

원핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


## 방법2

In [24]:
on_hot_df = pd.get_dummies(df[['label']])
df = pd.concat([df, on_hot_df], axis=1)

In [25]:
df

label  LabelEncoder Decoding  ...  label_선풍기  label_전자레인지  label_컴퓨터
0     TV             0       TV  ...          0            0          0
1    냉장고             1      냉장고  ...          0            0          0
2  전자레인지             4    전자레인지  ...          0            1          0
3    컴퓨터             5      컴퓨터  ...          0            0          1
4    선풍기             3      선풍기  ...          1            0          0
5    선풍기             3      선풍기  ...          1            0          0
6     믹서             2       믹서  ...          0            0          0
7     믹서             2       믹서  ...          0            0          0

[8 rows x 9 columns]